# Generated by Django 3.2.19 on 2023-06-13 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0002_auto_20230613_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='article',
        ),
    ]
